config/routes.rb
Rails.application.routes.draw do
  root 'users#index'
  post '/users/:id/sharecontacts' => 'users#share_contacts', as: :share_contacts
  get '/users/:id/contacts' => 'users#mes_contacts', as: 'user_contacts'
  get '/mailgroupe' => 'users#mailgroupe', as: 'mailgroupe'
  post 'users/mailgroupe' => 'users#postmail', as: "postmail"
  
  devise_for :users
  devise_for :contacts, controllers: { 
    registrations: 'contacts/registrations',
    sessions: 'contacts/sessions'
  }
  as :contact do
    get '/users/:id/contacts/new' => 'contacts/registrations#new', as: :new_contact
    post '/users/:id/contacts' => 'contacts/registrations#create', as: :create_contact
    
  end
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  resources :users
  resources :contacts do
    resources :notes
  end
  

end

app/models/user.rb
class User < ActiveRecord::Base
  has_and_belongs_to_many :contacts, -> { uniq }

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
         
  after_create :notify_by_email

  rails_admin do
   list do
       field :first_name
       field :last_name
       field :email
       field :function
   end
   edit do
       field :email
       field :password
       field :password_confirmation
       field :first_name
       field :last_name
       field :phone
       field :function
   end

   show do
       field :first_name
       field :last_name
       field :email
       field :function
       field :contacts

   end
  end

  def generate_password
    o = [('a'..'z'), ('A'..'Z')].map { |i| i.to_a }.flatten
    self.password = (0...8).map { o[rand(o.length)] }.join
    self.notify_by_email(self.password)
  end

  private

    def notify_by_email
      Confirmation.new_confirm(self, password).deliver_now
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
	include ApplicationHelper
	include UsersHelper
	before_action :is_admin, only: [:send_mail]
	before_action :authenticate_user!, except: [:index]
	def index
		
	end

	def mes_contacts
		@contacts = User.find(params[:id]).contacts
		@users = User.all
	end

	def show
    @url = url_for( :controller => 'contacts/registrations', :action => 'new' )
		@qr = qrcode
		@user = User.find(params[:id])
		@contacts = current_user.contacts
	end

	def edit
		@user = User.find(params[:id])
	end

	def update
		@user = User.find(params[:id])
		if @user.update(user_params)
				redirect_to root_path, notice: "\#{@user.first_name}\" a été modifié avec succés"
		else
			render 'edit', notice: "\#{@user.first_name}\" n'a pas été modifié"
		end
	end

	def mailgroupe
		@contacts = Contact.all
	end

	def postmail
		send_mail(params)
		redirect_to root_path
	end

	def share_contacts
		users = users_to_share(params)
		if users != nil && params[:contacts] != nil
			contacts = contact_array(params)
			users.each do |user|
				user.contacts << contacts
			end
		else
			render :mes_contacts
		end
		redirect_to user_contacts_path
	end

	private
	def user_params
		params.require(:user).permit(:first_name, :last_name, :function, :phone, :email, :password)
	end
end

app/helpers/users_helper.rb
module UsersHelper
  
  def group_to_send(params)
    tab_users = []
    params[:person].each do |k, v|
      if !!k.match(/^.+@.+$/) && v.include?("1")  
        tab_users <<Contact.where(email: k)
      end  
    end
    tab_users
  end

  def send_mail(params)
    users = group_to_send(params).flatten!
    message = message_to_send(params)
    subject = email_subject(params)

    users.map do |user|
      ContactMailer.mail_groupe(user, subject, message).deliver_now
    end
  end

  def message_to_send(params)
    message = ""
    params[:person].each do |k, v|
      if k == "body"
        message = v
      end
    end
    message
  end

  def email_subject(params)
    subject = ""
    params[:person].each do |k, v|
      if k == "subject"
        subject = v
      end
    end
    subject
  end

  def qrcode
    url = url_for( :controller => 'contacts/registrations', :action => 'new' )
    RQRCode::QRCode.new(url).to_img.resize(200, 200).to_data_url
  end

  def users_to_share(params)
    params[:persons].map {|k, v|
      if v == "1"
        User.find(k.to_i)
      end
      }.compact
  end

  def contact_array(params)
    params[:contacts].map {|i| Contact.find(i.to_i)}
  end


end

app/views/users/edit.html.erb
<h3>Modifier votre profil</h3>
<%= render 'form' %>

app/views/users/index.html.erb
<div class="row index_image">
  <div class="col-md-12 col-sm-12">
    <%= image_tag("bg_accueil-page1.jpg") %>
  </div>
  <div class="col-md-12 col-sm-12">
    <%= image_tag("bg_accueil-page2.jpg") %>
  </div>
</div>

app/views/users/mailgroupe.html.erb
<div class="container">
  <div class="row">
    <div class="col-sm-12 col-md-12 main">
      <h2 class="sub-header">Contacts</h2>
      <div class="table-responsive"></div>
        <%= form_tag("/users/mailgroupe") do %>
          <%= form_for :person do |f| %>
          <table class="table table-striped">
            <thead>
              <tr>
                <th>#</th>
                <th>Prenom</th>
                <th>Nom</th>
                <th>Fontion</th>
                <th>Email</th>
              </tr>
            </thead>
            <tbody>
              <% @contacts.each do |contact| %>
                <tr>
                  <td><%= f.check_box contact.email %></td>
                  <td><%= contact.first_name %></td>
                  <td><%= contact.last_name %></td>
                  <td><%= contact.function %></td>
                  <td><%= contact.email %></td>
                </tr>
              <% end %>
            </tbody>
          </table>
            <button type="button" class="btn btn-primary" data-toggle="modal" data-target="#exampleModal" data-whatever="@getbootstrap">Envoyer un mail groupé</button>
            <div class="modal fade" id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel">
              <div class="modal-dialog" role="document">
                <div class="modal-content">
                  <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                    <h4 class="modal-title" id="exampleModalLabel">New message</h4>
                  </div>
                  <div class="modal-body">
                    <form>
                      <div class="form-group">
                        <label for="recipient-name" class="control-label">Sujet:</label>
                        <%= f.text_field :subject, class: "form-control", id: "recipient-name" %>
                      </div>
                      <div class="form-group">
                        <label for="message-text" class="control-label">Message:</label>
                        <%= f.text_area :body, class: "form-control", id: "message-text" %>
                      </div>
                    </form>
                  </div>
                  <div class="modal-footer">
                    <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
                    <%= f.submit "Envoyer un mail", class: "btn btn-primary" %>
                  </div>
                </div>
              </div>
            </div>
          <% end %>
        <% end %>
      </div>
    </div>
  </div>
</div>

 

app/views/users/mes_contacts.html.erb
<div class="container"> 
  <div class ="row">
    <div class="col-sm-12 col-md-12 main">
      <h2 class="sub-header">Mes contacts</h2>
      <div class="table-responsive">
        <%= form_tag("sharecontacts") do %>
          <%= form_for :persons do |f| %>
            <table class="table table-striped">
              <thead>
                <tr>
                  <th>#</th>
                  <th>Prenom</th>
                  <th>Nom</th>
                  <th>Fontion</th>
                  <th>Email</th>
                  <th></th>
                </tr>
              </thead>
              <tbody>
                <% @contacts.each do |contact| %>
                  <tr>
                    <td>
                      <%= check_box_tag "contacts[]", contact.id %></td>
                    <td><%= contact.first_name %></td>
                    <td><%= contact.last_name %></td>
                    <td><%= contact.function %></td>
                    <td><%= contact.email %></td>

                    <td><%= link_to contact_path(contact.id) do %>
                      <i class="fa fa-comment">Ajouter une note</i>
                    <% end %>
                    </td>
                  </tr>
                <% end %>
              </tbody>
            </table>
            <button type="button" class="btn btn-primary" data-toggle="modal" data-target="#exampleModal" data-whatever="@getbootstrap">Partager un contact</button>
            <div class="modal fade" id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel">
              <div class="modal-dialog" role="document">
                <div class="modal-content">
                  <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                    <h4 class="modal-title" id="exampleModalLabel">Choisir un user</h4>
                  </div>
                  <div class="modal-body">
                    <form>
                    <table class="table table-striped">
                      <thead>
                        <tr>
                          <th>#</th>
                          <th>Prenom</th>
                          <th>Nom</th>
                          <th>Fontion</th>
                          <th>Email</th>
                        </tr>
                      </thead>
                      <tbody>
                        <% @users.each do |user| %>
                          <tr>
                            <td><%= f.check_box user.id %></td>
                            <td><%= user.first_name %></td>
                            <td><%= user.last_name %></td>
                            <td><%= user.function %></td>
                            <td><%= user.email %></td>
                          </tr>
                        <% end %>
                      </tbody>
                    </table>
                  </div>
                  <div class="modal-footer">
                    <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
                    <%= f.submit "Envoyer le(s) contact(s)", class: "btn btn-primary" %>
                  </div>
                </div>
              </div>
            </div> 
          <% end %>   
        <% end %>      
      </div>
    </div>
  </div>
</div>

app/views/users/show.html.erb
<div class = "container">
  <div class="row">
    <div class="col-sm-12 col-md-12 main panel panel-default">
      <div class="row panel panel-header user_bg">
        <p><%= image_tag @qr %></p>
        <a href=<%= @url %>><%= @url %></a>
        <h3>
          <% if @user.first_name.present? %>
            <%= @user.first_name %>
          <% end %>
          <% if @user.last_name.present? %>
            <%= @user.last_name %>
          <% end %>
        </h3>
        <p><%= @user.email %></p>
      </div>
        <div class="row panel panel-body mobile_menu">
          <div class="col-xs-12 col-sm-10 col-sm-offset-1 col-md-8 col-md-offset-2 placeholder">
            <% if current_user.is_admin? %>
            <%= link_to rails_admin_path do %>
            <div class ='coloradmin'>
              <i class="fa fa-wrench img-responsive"></i>
              <span>Administration</span>
            </div>
            <% end %>
            <% end %>
          </div>
          <!-- <div class="col-xs-12 col-sm-10 col-sm-offset-1 col-md-8 col-md-offset-2 placeholder">
            <%= link_to user_contacts_path do %>
            <div class ='colorprofil'>
              <i class="fa fa-user img-responsive"></i>
              <span>Mon profil</span>
            </div>
            <% end %>
          </div> -->
          <div <div class="col-xs-12 col-sm-10 col-sm-offset-1 col-md-8 col-md-offset-2 placeholder">
            <%= link_to "#" do %>
            <div class ='colorqrcode'>
              <i class="fa fa-qrcode img-responsive"></i>
              <span data-toggle="modal" data-target="#myModal2">Ma carte de visite</span>
            </div>
            <!-- Modal -->
            <div class="modal fade" id="myModal2" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
              <div class="modal-dialog" role="document">
                <div class="modal-content">
                  <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                    <h4 class="modal-title" id="myModalLabel">Scaner le qrcode</h4>
                  </div>
                  <div class="modal-body">
                    <%= image_tag @qr, class: "qrcode" %>
                  </div>
                  <div class="modal-footer">
                    <button type="button" class="btn btn-default" data-dismiss="modal">Fermer</button>
                  </div>
                </div>
              </div>
            </div>
            <% end %>
          </div>
          <div class="col-xs-12 col-sm-10 col-sm-offset-1 col-md-8 col-md-offset-2 placeholder">
            <%= link_to user_contacts_path do %>
            <div class="colorcontact">
              <i class="fa fa-users img-responsive"></i>
              <span>Mes contacts</span>
            </div>
            <% end %>
          </div>
          <div class="col-xs-12 col-sm-10 col-sm-offset-1 col-md-8 col-md-offset-2 placeholder">
            <%= link_to destroy_user_session_path, method: :delete do %>
            <div class = "colordeco">
              <i class="fa fa-envelope-o img-responsive"></i>
              <span>Deconnexion</span>
            </div>
            <% end %>
          </div>
        </div>
      <div>
    </div>
  </div>
</div>