config/routes.rb
Rails.application.routes.draw do
  root 'users#index'
  post '/users/:id/sharecontacts' => 'users#share_contacts', as: :share_contacts
  get '/users/:id/contacts' => 'users#mes_contacts', as: 'user_contacts'
  get '/mailgroupe' => 'users#mailgroupe', as: 'mailgroupe'
  post 'users/mailgroupe' => 'users#postmail', as: "postmail"
  
  devise_for :users
  devise_for :contacts, controllers: { 
    registrations: 'contacts/registrations',
    sessions: 'contacts/sessions'
  }
  as :contact do
    get '/users/:id/contacts/new' => 'contacts/registrations#new', as: :new_contact
    post '/users/:id/contacts' => 'contacts/registrations#create', as: :create_contact
    
  end
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  resources :users
  resources :contacts do
    resources :notes
  end
  

end

app/views/layouts/_footer.html.erb
<div class="footer">
  <div class="inner">
    <p>© <a href="#">Pays Perche</a>, by <a href="#">wcs</a>.</p>
    <p>
      <i class="fa fa-facebook-square"><a href="#"></a></i><i class="fa fa-twitter-square"><a href="#"></a></i>
    </p>
  </div>
</div>

app/views/layouts/_header_user.html.erb
<div class="bordure">
 <nav class="navbar navbar-inverse">
 <div class="container-fluid">
 <!-- Brand and toggle get grouped for better mobile display -->
 <div class="nav">
 <div class="navbar-header">
   <% if user_signed_in? %>
   <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
     <span class="sr-only">Toggle navigation</span>
     <span class="icon-bar"></span>
     <span class="icon-bar"></span>
     <span class="icon-bar"></span>
   </button>
   <a class="navbar-brand">Pays-Perche 3.0</a>
 </div>

 <!-- Collect the nav links, forms, and other content for toggling -->
 <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
    <ul class="nav navbar-nav">
    </ul>
     </li>
   </ul>
   <ul class="nav navbar-nav navbar-right">
     <li class="dropdown">
       <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Mon compte<span class="caret"></span></a>
       
       <ul class="dropdown-menu">
        <% if current_user.is_admin? %>
         <li> <%= link_to "Administration", rails_admin_path %></li>
        <% end %>
         <li> <%= link_to "Accueil", root_path %></li>
         <li> <%= link_to "Editer mon profil", edit_user_registration_path %></li>
         <li role="separator" class="divider"></li>
         <li>
           <%= link_to "Déconnexion", destroy_user_session_path, method: :delete %>
         </li>
       </ul>
     </li>
   </ul>
 </div><!-- /.navbar-collapse -->
 </div><!-- /.container-fluid -->
 </nav>
   <% else %>
     <%= link_to "S'enregistrer", new_user_registration_path, class: "add-party navbar-text navbar-right navbar-link" %>

     <%= link_to "Connexion", new_user_session_path, class: "add-party navbar-text navbar-right navbar-link" %>
   </ul>
 </div>
</div>
</nav>
<% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Perche 2.8</title>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
    <script type="text/javascript" src="http://ajax.googleapis.com/ajax/libs/jquery/1.8/jquery.min.js"></script>
  </head>
  <body>
    <nav class="navbar navbar-inverse navbar-fixed-top">
      <div class="container">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <span class="logo">
          </span>
          <%= link_to root_path, class: "navbar-brand" do %>
            <%=image_tag asset_path("logo_perche.png"), class: "logo" %>
          <% end %>
        </div>
        <div id="navbar" class="navbar-collapse collapse">
          <ul class="nav navbar-nav navbar-right">
            <% if user_signed_in? %>
              <li class="active"><%= link_to "Accueil", root_path %></li>

              <li class="desctop_menu">
                <%= link_to user_path(current_user, :anchor => "qrcode") do %>
                <div class ='desctop_menu'>
                  <span data-toggle="modal" data-target="#myModal" class="edem">Ma carte de visite</span>
                </div>
                <% end %>
              </li>

              <li><%= link_to "Mes contacts", user_contacts_path(current_user) %></li>
              <% if current_user.is_admin == true %>
                <li> <%= link_to "Envoyer un mail groupé", mailgroupe_path %></li>
                <li><%= link_to "Administration", rails_admin_path %></li>
              <% end %>
              <li class="dropdown">
                <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Mon compte<span class="caret"></span></a>
                <ul class="dropdown-menu">
                  <li> <%= link_to "Editer mon profil", edit_user_registration_path %></li>
                  <li role="separator" class="divider"></li>
                  <li><%= link_to "Déconnexion", destroy_user_session_path, method: :delete %></li>
                </ul>
              </li>
            <% else %>
              <li class="dropdown">
                <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Connexion<span class="caret"></span></a>
                <ul class="dropdown-menu">
                  <% if contact_signed_in? %>
                    <li><%= link_to "Editer mon compte", edit_contact_registration_path %></li>
                    <li><%= link_to "Deconnexion", destroy_contact_session_path, method: :delete %></li>
                  <% else %>
                    <li><%= link_to "Contact", new_contact_session_path %></li>
                  <% end %>
                  <li role="separator" class="divider"></li>
                  <li> <%= link_to "Utilisateur", new_user_session_path %></li>
                </ul>
              </li>
            <% end %>
          </ul>
        </div><!--/.nav-collapse -->
      </div>
    </nav>
    <div class="container">
      <% if notice %>
        <p class="alert alert-success"><%= notice %></p>
      <% end %>
      <% if alert %>
        <p class="alert alert-danger"><%= alert %></p>
      <% end %>
    <%= yield %>
    <%= render "layouts/footer" %>
    </div>
  </body>
</html>